version: 2.1
jobs:
  persist_to_workspace:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo Hello > output.txt
      - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - output.txt
  get_from_workspace:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "hear hello"
          command: cat output.txt
workflows:
  default:
    jobs:
      - persist_to_workspace
      - get_from_workspace:
          requires: 
            - persist_to_workspace
