version: 2.1
commands:
  print_pipeline_id:
    description: ""
    parameters:
      param: 
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo <<parameters.param>>

      
jobs:
  print_pipeline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -print_pipeline_id
  persist_to_workspace:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo Hello > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  get_from_workspace:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "hear hello"
          command: cat ~/output.txt
workflows:
  default:
    jobs:
      - print_pipeline_id
      - persist_to_workspace
      - get_from_workspace:
          requires: 
            - persist_to_workspace
